apiVersion: apps/v1
kind: Deployment
metadata:
  name: mscliente
  labels:
    app: mscliente
  namespace: app-micros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mscliente
  template:
    metadata:
      labels:
        app: mscliente
    spec:
      containers:
        - name: mscliente
          image: mauron/ms-cliente:6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mscliente-config
            - secretRef:
                name: mscliente-secret
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: mscliente-data
              mountPath: /data
          resources:
            limits:
              cpu: "500m"
              memory: "300Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: mscliente-data
          persistentVolumeClaim:
            claimName: pvc-local-mscliente
