spring.application.name=ms-cliente

# MongoDB Database
spring.data.mongodb.host=${MONGO_HOST}
spring.data.mongodb.port=${MONGO_PORT}
spring.data.mongodb.database=${MONGO_DATABASE}
spring.data.mongodb.username=${MONGO_USERNAME}
spring.data.mongodb.password=${MONGO_PASSWORD}
spring.data.mongodb.authentication-database=admin

server.port=8081

# External Services
facturas.service.url=${FACTURAS_SERVICE_URL}

feign.client.config.facturas-service.connectTimeout=5000
feign.client.config.facturas-service.readTimeout=5000
feign.client.config.facturas-service.loggerLevel=BASIC
feign.client.config.facturas-service.retryer=feign.Retryer.Default


feign.client.config.pagos-service.connectTimeout=6000
feign.client.config.pagos-service.readTimeout=2000
feign.client.config.pagos-service.loggerLevel=BASIC
feign.client.config.pagos-service.retryer=feign.Retryer.Default