spring.application.name=ms-factura

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://${HOST}:${PORT}/${DATABASE_NAME}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# pool de conexiones
spring.datasource.hikari.maximum-pool-size=${MAX_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${MIN_IDLE}
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000