spring.application.name=ms-factura

# H2 Database
spring.datasource.url=jdbc:h2:mem:factura_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (opcional - útil para debug)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# pool de conexiones
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000